version: '2.1'

services:
  ptoj-db:
    image: mongo:3.4.12
    container_name: ptoj-db
    restart: always
    volumes:
      - $PWD/migrations/db:/data/db
      - $PWD/migrations/backup:/data/backup

  ptoj-redis:
    image: redis:3.2.10
    container_name: ptoj-redis
    restart: always

  ptoj-app:
    image: ptoj-web-app
    container_name: ptoj-web-app
    build: .
    environment:
      NODE_ENV: production
      dbURL: 'http://ptoj-db:27017'
      redisURL: 'http://ptoj-redis:6379'
    ports:
      - '0.0.0.0:80:3000'
    volumes:
      - $PWD/log:/app/log
    depends_on:
      - ptoj-redis
      - ptoj-db
